name: Auto Deploy To-Do App (Apache)

on:
  push:
    branches:
      - main  # main 브랜치에 push 될 때마다 실행됨

jobs:
  deploy:
    runs-on: self-hosted  # VM에서 실행 중인 GitHub Runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy static files to Apache web root
        run: |
          sudo rm -rf /var/www/html/* /var/www/html/.* 2>/dev/null || true
          sudo cp -r public/* /var/www/html/
          sudo chown -R www-data:www-data /var/www/html
          sudo systemctl restart apache2


