name: Auto Deploy To-Do App

on:
  push:
    branches:
      - main  # main 브랜치에 push 될 때마다 실행됨

jobs:
  deploy:
    runs-on: self-hosted  # VM에서 실행 중인 GitHub Runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t todo-app .

      - name: Stop previous container (if exists)
        run: |
          docker stop todo-app || true
          docker rm todo-app || true

      - name: Run new Docker container
        run: docker run -d -p 27080:80 --name todo-app todo-app

