name: Auto Deploy To-Do App + Codee Report

on:
  push:
    branches:
      - main
      # main 브랜치에 push될 때 자동 실행

jobs:
  deploy:
    runs-on: self-hosted
    # 내 서버(VM)에 설치된 GitHub Runner 사용

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        # GitHub 리포지토리 코드를 체크아웃

      - name: Build C project with bear
        run: |
          cd src
          bear -- make
        # src/ 폴더에서 bear로 컴파일 감시 → compile_commands.json 생성

      - name: Generate Codee HTML report
        run: |
          export PATH=$PATH:/home/ptech/codee-2025.2-linux-x86_64/bin
          codee report src/compile_commands.json --out-dir out & sleep 30 && pkill -f "codee report" 
        # 경로를 직접설정한 후 html report 실행


      - name: Build Docker Image
        run: |
          docker build --no-cache -t codee-report-apache .
          docker build --no-cache -t todo-app .
        # Dockerfile로 새 이미지 생성

      - name: Stop previous todo-app container (if exists)
        run: |
          docker stop todo-app || true
          docker rm todo-app || true
        # todo-app 컨테이너 있으면 중지 + 삭제 (없어도 무시)

      - name: Stop previous codee-report container (if exists)
        run: |
          docker stop codee-report || true
          docker rm codee-report || true
        # 컨테이너 이름은 codee-report로 고정

      - name: Run new todo-app container
        run: |
          docker run -d -p 27080:80 --name todo-app todo-app

      - name: Run new codee-report container
        run: |
          docker run -d -p 8090:80 --name codee-report codee-report-apache
        # 이미지 이름: codee-report-apache
        # 컨테이너 이름: codee-report (고정)
