name: Auto Deploy To-Do App + Codee Report

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Clean and regenerate compile_commands.json
        run: |
          rm -f src/compile_commands.json
          cd src && bear -- make && cd ..

      - name: Clean previous Codee report
        run: rm -rf out

      - name: Generate new Codee HTML report
        run: |
          export PATH=$PATH:/home/ptech/codee-2025.2-linux-x86_64/bin
          codee report -p src/compile_commands.json --out-dir out & sleep 30

      - name: Append cache-busting version query to HTML
        run: |
          VERSION=$(date +%s)
          sed -i "s|style.css?v=[0-9]*|style.css?v=$VERSION|g" public/index.html || true
          sed -i "s|script.js?v=[0-9]*|script.js?v=$VERSION|g" public/index.html || true

      - name: Stop and remove unified-app 
        run: |
          docker stop unified-app || true
          docker rm unified-app || true

      - name: Build new Docker image without cache
        run: docker build --no-cache -t unified-app .

      - name: Run unified-app container on alternate port
        run: docker run -d -p 80:80 --name unified-app unified-app

